apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cloudjobs-application-search
  labels:
    name: cloudjobs-application-search
spec:
  selector:
    matchLabels:
      name: cloudjobs-application-search
  replicas: 1
  template:
    metadata:
      labels:
        name: cloudjobs-application-search
    spec:
      containers:
      - name: cloudjobs-application-search
        image: 700446461730.dkr.ecr.eu-west-2.amazonaws.com/meicm_ecr:cloudjobs_app_search_image_1.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8086
        resources: {}
        env:
          - name: PORT
            value: "8086"
        envFrom:
          - configMapRef:
              name: cloudjobs-application-database-configmap
