apiVersion: v1
kind: Service
metadata:
  name: cloudjobs-application-itjobs
  labels:
    name: cloudjobs-application-itjobs
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    name: cloudjobs-application-itjobs