apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cloudjobs-application-itjobs
  labels:
    name: cloudjobs-application-itjobs
spec:
  selector:
    matchLabels:
      name: cloudjobs-application-itjobs
  replicas: 1
  template:
    metadata:
      labels:
        name: cloudjobs-application-itjobs
    spec:
      containers:
      - name: cloudjobs-application-itjobs
        image: docker.io/library/cloudjobs_app_itjobs_image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        resources: {}
        env:
          - name: ITJOBS_KEY
            value: 02c5a7b5e6609e75e8a896bd54c2a160
          - name: ITJOBS_URL
            value: http://api.sandbox.itjobs.pt
          - name: PORT
            value: "8082"  
        
        
