services:
  cloudjobs_application_authentication:
    image: 700446461730.dkr.ecr.eu-west-2.amazonaws.com/meicm_ecr:cloudjobs_app_authentication_image_1.0.5
    build:
      context: ../../src/
      dockerfile: ../deployment/kubernetes/services/authentication/Dockerfile
  #cloudjobs_application_frontend:
  #  image: 700446461730.dkr.ecr.eu-west-2.amazonaws.com/meicm_ecr:cloudjobs_app_frontend_image_1.0.0
  #  build:
  #    context: ../../src/
  #    dockerfile: ../deployment/kubernetes/services/frontend/Dockerfile    
  cloudjobs_application_itjobs:
    image: 700446461730.dkr.ecr.eu-west-2.amazonaws.com/meicm_ecr:cloudjobs_app_itjobs_image_1.0.2
    build:
      context: ../../src/
      dockerfile: ../deployment/kubernetes/services/itjobs/Dockerfile
  cloudjobs_application_scheduler:
    image: 700446461730.dkr.ecr.eu-west-2.amazonaws.com/meicm_ecr:cloudjobs_app_scheduler_image_1.2.1
    build:
      context: ../../src/
      dockerfile: ../deployment/kubernetes/services/scheduler/Dockerfile
  cloudjobs_application_statistics:
    image: 700446461730.dkr.ecr.eu-west-2.amazonaws.com/meicm_ecr:cloudjobs_app_statistics_image_1.0.2
    build:
      context: ../../src/
      dockerfile: ../deployment/kubernetes/services/statistics/Dockerfile
  cloudjobs_application_gatherkeywords:
    image: 700446461730.dkr.ecr.eu-west-2.amazonaws.com/meicm_ecr:cloudjobs_app_gatherkeywords_image_1.0.3
    build:
      context: ../../src/
      dockerfile: ../deployment/kubernetes/services/gatherkeywords/Dockerfile
  cloudjobs_application_search:
    image: 700446461730.dkr.ecr.eu-west-2.amazonaws.com/meicm_ecr:cloudjobs_app_search_image_1.0.2
    container_name: cloudjobs_application_search
    build:
      context: ../../src/
      dockerfile: ../deployment/kubernetes/services/search/Dockerfile
                    
  