apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cloudjobs-application-gatherkeywords
  labels:
    name: cloudjobs-application-gatherkeywords
spec:
  selector:
    matchLabels:
      name: cloudjobs-application-gatherkeywords
  replicas: 1
  template:
    metadata:
      labels:
        name: cloudjobs-application-gatherkeywords
    spec:
      containers:
      - name: cloudjobs-application-gatherkeywords
        image: docker.io/library/cloudjobs_app_gatherkeywords_image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        resources: {}
        env:
            - name: PORT
              value: "8085"
        envFrom:
          - configMapRef:
              name: cloudjobs-application-database-configmap
