apiVersion: v1
kind: Service
metadata:
  name: cloudjobs-application-authentication
  labels:
    name: cloudjobs-application-authentication
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    name: cloudjobs-application-authentication